import type { Car, Tariff, RentalOrder, MaintenanceWindow, Client, DashboardStats } from "./types";

export const mockCars: Car[] = [
  {
    id: "car-1",
    vin: "1HGBH41JXMN109186",
    plateNumber: "ABC-1234",
    make: "BMW",
    model: "3 Series",
    year: 2024,
    carClass: "BUSINESS",
    status: "AVAILABLE",
    imageUrl: "/placeholder.svg?height=200&width=320",
    features: ["GPS Navigation", "Leather Seats", "Bluetooth", "Backup Camera", "Heated Seats"],
    seats: 5,
    transmission: "AUTOMATIC",
    fuelType: "PETROL",
    dailyRate: 89,
  },
  {
    id: "car-2",
    vin: "2HGBH41JXMN109187",
    plateNumber: "XYZ-5678",
    make: "Mercedes-Benz",
    model: "E-Class",
    year: 2024,
    carClass: "PREMIUM",
    status: "AVAILABLE",
    imageUrl: "/placeholder.svg?height=200&width=320",
    features: ["GPS Navigation", "Leather Seats", "Sunroof", "Premium Sound", "Massage Seats"],
    seats: 5,
    transmission: "AUTOMATIC",
    fuelType: "HYBRID",
    dailyRate: 149,
  },
  {
    id: "car-3",
    vin: "3HGBH41JXMN109188",
    plateNumber: "DEF-9012",
    make: "Toyota",
    model: "Camry",
    year: 2024,
    carClass: "COMFORT",
    status: "RENTED",
    imageUrl: "/placeholder.svg?height=200&width=320",
    features: ["GPS Navigation", "Bluetooth", "Backup Camera", "Cruise Control"],
    seats: 5,
    transmission: "AUTOMATIC",
    fuelType: "HYBRID",
    dailyRate: 59,
  },
  {
    id: "car-4",
    vin: "4HGBH41JXMN109189",
    plateNumber: "GHI-3456",
    make: "Honda",
    model: "Civic",
    year: 2024,
    carClass: "ECONOMY",
    status: "AVAILABLE",
    imageUrl: "/placeholder.svg?height=200&width=320",
    features: ["Bluetooth", "Backup Camera", "USB Charging"],
    seats: 5,
    transmission: "AUTOMATIC",
    fuelType: "PETROL",
    dailyRate: 39,
  },
  {
    id: "car-5",
    vin: "5HGBH41JXMN109190",
    plateNumber: "JKL-7890",
    make: "Range Rover",
    model: "Sport",
    year: 2024,
    carClass: "SUV",
    status: "MAINTENANCE",
    imageUrl: "/placeholder.svg?height=200&width=320",
    features: ["GPS Navigation", "Leather Seats", "4WD", "Panoramic Roof", "Air Suspension"],
    seats: 7,
    transmission: "AUTOMATIC",
    fuelType: "DIESEL",
    dailyRate: 179,
  },
  {
    id: "car-6",
    vin: "6HGBH41JXMN109191",
    plateNumber: "MNO-1234",
    make: "Audi",
    model: "A4",
    year: 2024,
    carClass: "BUSINESS",
    status: "AVAILABLE",
    imageUrl: "/placeholder.svg?height=200&width=320",
    features: ["GPS Navigation", "Leather Seats", "Virtual Cockpit", "Wireless Charging"],
    seats: 5,
    transmission: "AUTOMATIC",
    fuelType: "PETROL",
    dailyRate: 95,
  },
  {
    id: "car-7",
    vin: "7HGBH41JXMN109192",
    plateNumber: "PQR-5678",
    make: "Tesla",
    model: "Model 3",
    year: 2024,
    carClass: "PREMIUM",
    status: "RESERVED",
    imageUrl: "/placeholder.svg?height=200&width=320",
    features: ["Autopilot", "Premium Sound", "Glass Roof", "Supercharger Access"],
    seats: 5,
    transmission: "AUTOMATIC",
    fuelType: "ELECTRIC",
    dailyRate: 129,
  },
  {
    id: "car-8",
    vin: "8HGBH41JXMN109193",
    plateNumber: "STU-9012",
    make: "Volkswagen",
    model: "Golf",
    year: 2024,
    carClass: "ECONOMY",
    status: "AVAILABLE",
    imageUrl: "/placeholder.svg?height=200&width=320",
    features: ["Bluetooth", "Apple CarPlay", "Backup Camera"],
    seats: 5,
    transmission: "MANUAL",
    fuelType: "PETROL",
    dailyRate: 35,
  },
];

export const mockTariffs: Tariff[] = [
  {
    id: "tariff-1",
    name: "Economy Basic",
    carClass: "ECONOMY",
    basePrice: 15,
    dailyPrice: 35,
    weeklyDiscount: 10,
    monthlyDiscount: 20,
    mileageLimit: 200,
    extraMileageCost: 0.25,
    insuranceIncluded: true,
    description: "Perfect for budget-conscious travelers. Basic coverage included.",
  },
  {
    id: "tariff-2",
    name: "Comfort Plus",
    carClass: "COMFORT",
    basePrice: 20,
    dailyPrice: 59,
    weeklyDiscount: 12,
    monthlyDiscount: 22,
    mileageLimit: 250,
    extraMileageCost: 0.30,
    insuranceIncluded: true,
    description: "Enhanced comfort for longer journeys. Full insurance coverage.",
  },
  {
    id: "tariff-3",
    name: "Business Pro",
    carClass: "BUSINESS",
    basePrice: 30,
    dailyPrice: 89,
    weeklyDiscount: 15,
    monthlyDiscount: 25,
    mileageLimit: 300,
    extraMileageCost: 0.35,
    insuranceIncluded: true,
    description: "Professional-grade vehicles for business trips. Premium support.",
  },
  {
    id: "tariff-4",
    name: "Premium Elite",
    carClass: "PREMIUM",
    basePrice: 50,
    dailyPrice: 149,
    weeklyDiscount: 15,
    monthlyDiscount: 25,
    mileageLimit: 400,
    extraMileageCost: 0.45,
    insuranceIncluded: true,
    description: "Luxury experience with top-tier vehicles. VIP treatment included.",
  },
  {
    id: "tariff-5",
    name: "SUV Adventure",
    carClass: "SUV",
    basePrice: 45,
    dailyPrice: 179,
    weeklyDiscount: 12,
    monthlyDiscount: 20,
    mileageLimit: 350,
    extraMileageCost: 0.50,
    insuranceIncluded: true,
    description: "Spacious SUVs for family trips and adventures. Off-road ready.",
  },
];

export const mockClients: Client[] = [
  {
    id: "client-1",
    firstName: "John",
    lastName: "Smith",
    email: "john.smith@email.com",
    phone: "+1 (555) 123-4567",
    licenseNumber: "D1234567",
    licenseExpiry: "2027-05-15",
    totalRentals: 5,
    createdAt: "2024-01-15",
  },
  {
    id: "client-2",
    firstName: "Sarah",
    lastName: "Johnson",
    email: "sarah.j@email.com",
    phone: "+1 (555) 987-6543",
    licenseNumber: "D7654321",
    licenseExpiry: "2026-08-20",
    totalRentals: 12,
    createdAt: "2023-06-10",
  },
];

export const mockRentalOrders: RentalOrder[] = [
  {
    id: "rental-1",
    carId: "car-3",
    car: mockCars[2],
    clientId: "client-1",
    client: mockClients[0],
    tariffId: "tariff-2",
    tariff: mockTariffs[1],
    status: "ISSUED",
    pickupLocation: "Downtown Office",
    returnLocation: "Airport Terminal",
    startDate: "2026-03-28",
    endDate: "2026-04-02",
    totalDays: 5,
    basePrice: 20,
    totalPrice: 315,
    createdAt: "2026-03-25",
    statusHistory: [
      { status: "CREATED", timestamp: "2026-03-25T10:00:00Z" },
      { status: "CONFIRMED", timestamp: "2026-03-25T14:30:00Z" },
      { status: "ISSUED", timestamp: "2026-03-28T09:00:00Z" },
    ],
  },
  {
    id: "rental-2",
    carId: "car-7",
    car: mockCars[6],
    clientId: "client-2",
    client: mockClients[1],
    tariffId: "tariff-4",
    tariff: mockTariffs[3],
    status: "CONFIRMED",
    pickupLocation: "Airport Terminal",
    returnLocation: "Airport Terminal",
    startDate: "2026-04-01",
    endDate: "2026-04-05",
    totalDays: 4,
    basePrice: 50,
    totalPrice: 646,
    createdAt: "2026-03-29",
    statusHistory: [
      { status: "CREATED", timestamp: "2026-03-29T15:00:00Z" },
      { status: "CONFIRMED", timestamp: "2026-03-29T16:00:00Z" },
    ],
  },
  {
    id: "rental-3",
    carId: "car-1",
    car: mockCars[0],
    clientId: "client-1",
    client: mockClients[0],
    tariffId: "tariff-3",
    tariff: mockTariffs[2],
    status: "COMPLETED",
    pickupLocation: "Downtown Office",
    returnLocation: "Downtown Office",
    startDate: "2026-03-15",
    endDate: "2026-03-18",
    actualReturnDate: "2026-03-18",
    totalDays: 3,
    basePrice: 30,
    totalPrice: 297,
    createdAt: "2026-03-10",
    statusHistory: [
      { status: "CREATED", timestamp: "2026-03-10T09:00:00Z" },
      { status: "CONFIRMED", timestamp: "2026-03-10T11:00:00Z" },
      { status: "ISSUED", timestamp: "2026-03-15T10:00:00Z" },
      { status: "COMPLETED", timestamp: "2026-03-18T14:30:00Z" },
    ],
  },
  {
    id: "rental-4",
    carId: "car-4",
    car: mockCars[3],
    clientId: "client-2",
    client: mockClients[1],
    tariffId: "tariff-1",
    tariff: mockTariffs[0],
    status: "CANCELLED",
    pickupLocation: "City Center",
    returnLocation: "City Center",
    startDate: "2026-03-20",
    endDate: "2026-03-22",
    totalDays: 2,
    basePrice: 15,
    totalPrice: 85,
    createdAt: "2026-03-18",
    statusHistory: [
      { status: "CREATED", timestamp: "2026-03-18T12:00:00Z" },
      { status: "CANCELLED", timestamp: "2026-03-19T08:00:00Z", note: "Customer request" },
    ],
  },
];

export const mockMaintenanceWindows: MaintenanceWindow[] = [
  {
    id: "maint-1",
    carId: "car-5",
    car: mockCars[4],
    serviceType: "Regular Service",
    description: "Oil change, brake inspection, tire rotation",
    startDate: "2026-03-30",
    endDate: "2026-04-02",
    status: "IN_PROGRESS",
    cost: 450,
  },
  {
    id: "maint-2",
    carId: "car-2",
    car: mockCars[1],
    serviceType: "Annual Inspection",
    description: "Full vehicle inspection and certification",
    startDate: "2026-04-05",
    endDate: "2026-04-06",
    status: "SCHEDULED",
    cost: 200,
  },
  {
    id: "maint-3",
    carId: "car-6",
    car: mockCars[5],
    serviceType: "Tire Replacement",
    description: "Replace all four tires with premium summer tires",
    startDate: "2026-03-25",
    endDate: "2026-03-26",
    status: "COMPLETED",
    cost: 800,
  },
];

export const mockDashboardStats: DashboardStats = {
  totalCars: 8,
  availableCars: 4,
  activeRentals: 2,
  carsInMaintenance: 1,
  monthlyRevenue: 12450,
  pendingOrders: 3,
};

export const locations = [
  "Downtown Office",
  "Airport Terminal",
  "City Center",
  "Train Station",
  "Hotel District",
  "Business Park",
];
